import TelegramBot from 'node-telegram-bot-api';
// Add dotenv at the top
import * as dotenv from 'dotenv';
import path from 'path';
import http from 'http';

// Load .env.local first (overrides)
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });
// Load .env (backups)
dotenv.config();

import { analyzeWithGroq } from '../lib/groq-ai';
import { getMarketData, formatMarketDataForAI, FOREX_PAIRS } from '../lib/market-data';

// --- CONFIGURATION ---
const TOKEN = process.env.TELEGRAM_BOT_TOKEN || ''; // User needs to set this in .env
const VVIP_CHAT_IDS = (process.env.VVIP_CHAT_IDS || '').split(',').map(id => id.trim());

// Initialize Bot
const bot = new TelegramBot(TOKEN, { polling: true });

console.log('🚀 ARRA7 VVIP Telegram Bot Started...');
console.log('👉 Send /start to the bot to begin.');

if (!TOKEN) {
    console.error('❌ ERROR: TELEGRAM_BOT_TOKEN is missing in .env');
    process.exit(1);
}

// --- HELPER FUNCTIONS ---

/**
 * Check if user is VVIP
 * In production, query the database. For now, check env/hardcoded list + allow all for testing if empty.
 */
async function isUserVVIP(chatId: number): Promise<boolean> {
    // 1. Dev Mode: If no VVIPs defined, allow everyone (for testing)
    if (VVIP_CHAT_IDS.length === 0 || (VVIP_CHAT_IDS.length === 1 && VVIP_CHAT_IDS[0] === '')) {
        return true;
    }

    // 2. Check Whitelist
    return VVIP_CHAT_IDS.includes(chatId.toString());
}

/**
 * Clean & Format AI Response for Telegram (Markdown/HTML)
 * Telegram supports basic HTML: <b>, <i>, <code>, <pre>
 */
function formatForTelegram(text: string): string {
    let formatted = text;

    // Remove unsupported Markdown bold (**text**) -> <b>text</b>
    formatted = formatted.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');

    // Remove headers (###)
    formatted = formatted.replace(/###\s*(.*)/g, '\n<b>$1</b>');
    formatted = formatted.replace(/#\s*(.*)/g, '\n<b>$1</b>');

    // Remove unsupported tags
    formatted = formatted.replace(/<br>/g, '\n');
    formatted = formatted.replace(/<[^>]*>/g, ''); // Strip all other HTML tags valid in web but not TG

    // Add Footer
    formatted += '\n\n<i>Generated by ARRA7 Quantum AI</i>';

    return formatted;
}

// --- COMMAND HANDLERS ---

// /start
bot.onText(/\/start/, async (msg) => {
    const chatId = msg.chat.id;
    const isVvip = await isUserVVIP(chatId);

    if (!isVvip) {
        bot.sendMessage(chatId, `❌ <b>ACCESS DENIED</b>\n\nMaaf, bot ini khusus untuk member <b>VVIP ARRA7</b>.\nID Telegram Anda: <code>${chatId}</code>\n\nSilakan hubungi admin untuk pendaftaran.`, { parse_mode: 'HTML' });
        return;
    }

    bot.sendMessage(chatId,
        `🤖 <b>WELCOME BOSS!</b>\n\n` +
        `Saya adalah Asisten Trading Pribadi Anda.\n\n` +
        `<b>Perintah Tersedia:</b>\n` +
        `/analisa [PAIR] [TF] - Analisa mendalam AI\n` +
        `/price [PAIR] - Cek harga real-time\n` +
        `/help - Bantuan\n\n` +
        `<i>Contoh: /analisa XAUUSD H1</i>`,
        { parse_mode: 'HTML' }
    );
});

// /help
bot.onText(/\/help/, (msg) => {
    const chatId = msg.chat.id;
    bot.sendMessage(chatId,
        `📋 <b>PANDUAN PENGGUNAAN</b>\n\n` +
        `1. <b>Analisa Market</b>\n` +
        `Ketik: <code>/analisa XAUUSD</code> (Default H1)\n` +
        `Ketik: <code>/analisa BTCUSD M15</code> (Spesifik)\n\n` +
        `2. <b>Cek Harga</b>\n` +
        `Ketik: <code>/price XAUUSD</code>\n\n` +
        `3. <b>Pasangan (Pair) Support</b>\n` +
        `Forex: EURUSD, GBPUSD, USDJPY, dll\n` +
        `Crypto: BTCUSD, ETHUSD, dll\n` +
        `Gold: XAUUSD`,
        { parse_mode: 'HTML' }
    );
});

// /price [PAIR]
bot.onText(/\/price (.+)/, async (msg, match) => {
    const chatId = msg.chat.id;
    if (!await isUserVVIP(chatId)) return;

    const rawPair = match ? match[1] : '';
    const pair = rawPair.toUpperCase().trim();

    // Mapping simple names
    let targetPair: any = pair;
    if (pair === 'GOLD') targetPair = 'XAUUSD';
    if (pair === 'BITCOIN') targetPair = 'BTCUSD';

    // Validate
    if (!FOREX_PAIRS[targetPair as keyof typeof FOREX_PAIRS]) {
        bot.sendMessage(chatId, `⚠️ Pair <b>${pair}</b> tidak ditemukan.`, { parse_mode: 'HTML' });
        return;
    }

    try {
        const data = await getMarketData(targetPair, '1m');
        const direction = data.change_percent >= 0 ? '🟢' : '🔴';

        bot.sendMessage(chatId,
            `💰 <b>LIVE PRICE: ${data.name}</b>\n\n` +
            `Price: <code>${data.current_price}</code>\n` +
            `Change: ${direction} <b>${data.change_percent}%</b>\n` +
            `High: ${data.high} | Low: ${data.low}\n\n` +
            `Freshness: ${data.freshnessSeconds}s ago`,
            { parse_mode: 'HTML' }
        );
    } catch (e: any) {
        bot.sendMessage(chatId, `❌ Gagal mengambil data: ${e.message}`);
    }
});

// /analisa [PAIR] [TF]
bot.onText(/\/analisa (.+)/, async (msg, match) => {
    const chatId = msg.chat.id;
    if (!await isUserVVIP(chatId)) return; // Silent fail if not VVIP to avoid spam response? Or polite deny.
    // Let's rely on /start message for deny. Here we can check again.
    if (!await isUserVVIP(chatId)) {
        bot.sendMessage(chatId, "❌ Akses Ditolak.");
        return;
    }

    const input = match ? match[1].toUpperCase().split(' ') : [];
    let pair = input[0];
    let tf = input[1] || 'H1';

    // Alias handling
    if (pair === 'GOLD' || pair === 'EMAS') pair = 'XAUUSD';

    // Validate
    if (!FOREX_PAIRS[pair as keyof typeof FOREX_PAIRS]) {
        bot.sendMessage(chatId, `⚠️ Pair <b>${pair}</b> tidak valid.`, { parse_mode: 'HTML' });
        return;
    }

    // Processing Message
    const loadingMsg = await bot.sendMessage(chatId, `🧠 <b>Sedang Menganalisa ${pair} (${tf})...</b>\nMohon tunggu sebentar...`, { parse_mode: 'HTML' });

    try {
        // 1. Get Data
        const marketData = await getMarketData(pair as any, tf as any);
        const marketText = formatMarketDataForAI(marketData, tf);

        // 2. Call AI
        const aiResult = await analyzeWithGroq(marketText);

        if (aiResult.success && aiResult.analysis) {
            const reply = formatForTelegram(aiResult.analysis);

            // Delete loading message (optional, or edit it)
            bot.deleteMessage(chatId, loadingMsg.message_id);

            // Send Result
            bot.sendMessage(chatId, reply, { parse_mode: 'HTML' });
        } else {
            bot.editMessageText(`❌ Maaf, AI gagal menganalisa. Error: ${aiResult.error}`, { chat_id: chatId, message_id: loadingMsg.message_id });
        }

    } catch (e: any) {
        bot.editMessageText(`❌ Terjadi kesalahan sistem: ${e.message}`, { chat_id: chatId, message_id: loadingMsg.message_id });
    }
});

// Log Errors
bot.on('polling_error', (error) => {
    console.log(error.code);  // => 'EFATAL'
});

// --- HEALTH CHECK SERVER (For Hugging Face / Render) ---
const PORT = process.env.PORT || 7860;
http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.write('ARRA7 Telegram Bot is Running! 🚀');
    res.end();
}).listen(PORT, () => {
    console.log(`✅ Health check server listening on port ${PORT}`);
});
