import TelegramBot from 'node-telegram-bot-api';
// Add dotenv at the top
import * as dotenv from 'dotenv';
import path from 'path';
import http from 'http';

// Load .env.local first (overrides)
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });
// Load .env (backups)
dotenv.config();

import { analyzeWithGroq, interpretUserMessage, chatWithAI } from '../lib/groq-ai';
import { getMarketData, formatMarketDataForAI, FOREX_PAIRS } from '../lib/market-data';

// --- CONFIGURATION ---
const TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const VVIP_CHAT_IDS = (process.env.VVIP_CHAT_IDS || '').split(',').map(id => id.trim());

// Initialize Bot
const bot = new TelegramBot(TOKEN, { polling: true });

console.log('🚀 ARRA7 VVIP Telegram Bot (Smart Agent) Started...');

if (!TOKEN) {
    console.error('❌ ERROR: TELEGRAM_BOT_TOKEN is missing in .env');
    process.exit(1);
}

// --- HELPER FUNCTIONS ---

async function isUserVVIP(chatId: number): Promise<boolean> {
    if (VVIP_CHAT_IDS.length === 0 || (VVIP_CHAT_IDS.length === 1 && VVIP_CHAT_IDS[0] === '')) {
        return true;
    }
    return VVIP_CHAT_IDS.includes(chatId.toString());
}

function formatForTelegram(text: string): string {
    let formatted = text;
    formatted = formatted.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');
    formatted = formatted.replace(/###\s*(.*)/g, '\n<b>$1</b>');
    formatted = formatted.replace(/#\s*(.*)/g, '\n<b>$1</b>');
    formatted = formatted.replace(/<br>/g, '\n');
    formatted = formatted.replace(/<[^>]*>/g, '');
    formatted += '\n\n<i>Generated by ARRA7 Quantum AI</i>';
    return formatted;
}

// --- SMART MESSAGE HANDLER ---

bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    const text = msg.text;

    if (!text) return;

    // 1. Security Check
    if (!await isUserVVIP(chatId)) {
        bot.sendMessage(chatId, `❌ <b>ACCESS DENIED</b>\n\nMaaf, bot ini khusus untuk member <b>VVIP ARRA7</b>.\nID Anda: <code>${chatId}</code>`, { parse_mode: 'HTML' });
        return;
    }

    // 2. Commands (Optional Override)
    if (text.startsWith('/start')) {
        bot.sendMessage(chatId, `🤖 <b>ARRA7 SMART AGENT</b>\n\nSaya sudah upgrade! tidak perlu ketik command kaku lagi.\n\n<b>Coba Chat Saya:</b>\n"Bro minta signal gold M15"\n"Analisa BTC sekarang"\n"Harga ETH berapa?"\n"Tips trading hari ini apa?"`, { parse_mode: 'HTML' });
        return;
    }

    // 3. NLP PROCESSING
    // Show "typing" status
    bot.sendChatAction(chatId, 'typing');

    try {
        // A. Classify Intent
        const interpretation = await interpretUserMessage(text);
        console.log(`[NLP] Intent: ${interpretation.intent}`, interpretation);

        // B. Handle Intent
        switch (interpretation.intent) {
            case 'ANALYSIS':
                await handleAnalysis(chatId, interpretation.pair, interpretation.timeframe);
                break;
            case 'PRICE':
                await handlePrice(chatId, interpretation.pair);
                break;
            case 'CHAT':
                const reply = await chatWithAI(text);
                bot.sendMessage(chatId, reply);
                break;
            default:
                // Fallback
                bot.sendMessage(chatId, "Maaf bos, saya bingung. Coba tanya lagi yang jelas.");
        }

    } catch (error) {
        console.error('Bot Error:', error);
        bot.sendMessage(chatId, "❌ Ada masalah sistem bos. Coba lagi nanti.");
    }
});

// --- ACTION HANDLERS ---

async function handleAnalysis(chatId: number, pair?: string, tf?: string) {
    // Default values if NLP missed them
    const targetPair = (pair || 'XAUUSD').toUpperCase();
    const timeframe = (tf || 'H1').toUpperCase();

    // Map common aliases
    let finalPair = targetPair;
    if (finalPair === 'GOLD' || finalPair === 'EMAS') finalPair = 'XAUUSD';
    if (finalPair === 'BITCOIN') finalPair = 'BTCUSD';

    // Validate
    if (!FOREX_PAIRS[finalPair as keyof typeof FOREX_PAIRS]) {
        bot.sendMessage(chatId, `⚠️ Pair <b>${finalPair}</b> tidak valid bos. Coba pair major saja.`, { parse_mode: 'HTML' });
        return;
    }

    const loadingMsg = await bot.sendMessage(chatId, `🧠 <b>Sedang Analisa ${finalPair} (${timeframe})...</b>`, { parse_mode: 'HTML' });

    try {
        const marketData = await getMarketData(finalPair as any, timeframe as any);
        const marketText = formatMarketDataForAI(marketData, timeframe);
        const aiResult = await analyzeWithGroq(marketText);

        if (aiResult.success && aiResult.analysis) {
            const reply = formatForTelegram(aiResult.analysis);
            bot.deleteMessage(chatId, loadingMsg.message_id);
            bot.sendMessage(chatId, reply, { parse_mode: 'HTML' });
        } else {
            bot.editMessageText(`❌ Gagal analisa bos. Error AI.`, { chat_id: chatId, message_id: loadingMsg.message_id });
        }
    } catch (e: any) {
        bot.editMessageText(`❌ Error Data: ${e.message}`, { chat_id: chatId, message_id: loadingMsg.message_id });
    }
}

async function handlePrice(chatId: number, pair?: string) {
    const targetPair = (pair || 'XAUUSD').toUpperCase();

    // Map common aliases
    let finalPair = targetPair;
    if (finalPair === 'GOLD' || finalPair === 'EMAS') finalPair = 'XAUUSD';

    if (!FOREX_PAIRS[finalPair as keyof typeof FOREX_PAIRS]) {
        bot.sendMessage(chatId, `⚠️ Pair <b>${finalPair}</b> gak ketemu bos.`, { parse_mode: 'HTML' });
        return;
    }

    try {
        const data = await getMarketData(finalPair, '1m');
        const direction = data.change_percent >= 0 ? '🟢' : '🔴';
        bot.sendMessage(chatId, `💰 <b>${data.name}</b>: <code>${data.current_price}</code> (${direction} ${data.change_percent}%)`, { parse_mode: 'HTML' });
    } catch (e) {
        bot.sendMessage(chatId, "Gagal ambil harga bos.");
    }
}

// Log Errors with more detail
bot.on('polling_error', (error) => {
    // Ignore harmless "ETELEGRAM: 409 Conflict" errors (happens when multiple instances run)
    if (error.code === 'ETELEGRAM' && error.message.includes('409 Conflict')) return;

    console.error(`[Polling Error] Code: ${error.code}, Msg: ${error.message}`);
});

// --- KEEP-ALIVE MECHANISM ---
// Pings the Hugging Face URL to prevent sleep (Best effort for free tier)
const APP_URL = 'https://arratujuhkreasi-arra7-vip-bot.hf.space';
setInterval(() => {
    http.get(APP_URL, (res) => {
        console.log(`[Keep-Alive] Ping sent. Status: ${res.statusCode}`);
    }).on('error', (err) => {
        console.error(`[Keep-Alive] Ping failed: ${err.message}`);
    });
}, 5 * 60 * 1000); // Every 5 minutes

// --- HEALTH CHECK SERVER (For Hugging Face / Render) ---
const PORT = process.env.PORT || 7860;
http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.write('ARRA7 Telegram Bot is Running! 🚀');
    res.end();
}).listen(PORT, () => {
    console.log(`✅ Health check server listening on port ${PORT}`);
});
