import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import getTursoClient from '@/lib/turso';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.email) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const turso = getTursoClient();
        if (!turso) return NextResponse.json({ error: 'DB error' }, { status: 500 });

        const { searchParams } = new URL(request.url);
        const mode = searchParams.get('mode') || 'follower'; // 'follower' | 'provider'
        const status = searchParams.get('status'); // 'open' | 'closed'

        const userResult = await turso.execute({
            sql: 'SELECT id FROM users WHERE email = ?',
            args: [session.user.email]
        });

        if (userResult.rows.length === 0) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        const userId = userResult.rows[0].id as string;

        if (mode === 'follower') {
            // Fetch copied positions for the follower
            let query = `
                SELECT cp.*, sp.display_name as provider_name 
                FROM copied_positions cp
                JOIN copy_relationships cr ON cp.copy_relationship_id = cr.id
                JOIN signal_providers sp ON cr.provider_id = sp.id
                WHERE cr.follower_user_id = ?
            `;
            const args: any[] = [userId];

            if (status) {
                query += ` AND cp.status = ?`;
                args.push(status);
            }

            query += ` ORDER BY cp.opened_at DESC LIMIT 100`;

            const trades = await turso.execute({ sql: query, args });
            return NextResponse.json({ trades: trades.rows });
        } else if (mode === 'provider') {
            // Fetch signals generated by the provider
            const providerResult = await turso.execute({
                sql: 'SELECT id FROM signal_providers WHERE user_id = ? AND is_active = 1',
                args: [userId]
            });

            if (providerResult.rows.length === 0) {
                return NextResponse.json({ trades: [] });
            }

            const providerId = providerResult.rows[0].id as string;

            let query = `SELECT * FROM provider_signals WHERE provider_id = ?`;
            const args: any[] = [providerId];

            if (status) {
                if (status === 'open') {
                    query += ` AND status = 'active'`;
                } else if (status === 'closed') {
                    query += ` AND status = 'closed'`;
                }
            }

            query += ` ORDER BY created_at DESC LIMIT 100`;

            const trades = await turso.execute({ sql: query, args });

            // Map provider_signals fields to match copied_positions format for the UI
            const mappedTrades = trades.rows.map((row: any) => ({
                id: row.id,
                symbol: row.pair,
                position_type: row.action,
                lot_size: row.lot_size,
                entry_price: row.entry_price,
                exit_price: null, // Since we don't have exit price in signals typically, or it's implicitly hit TP/SL
                stop_loss: row.stop_loss,
                take_profit: row.take_profit,
                profit_loss: row.result_pips || 0, // Using pips as proxy for profit
                status: row.status === 'active' ? 'open' : 'closed',
                opened_at: row.created_at,
                closed_at: row.closed_at,
                provider_name: 'Me (Provider)',
                is_signal: true // Flag to tell UI this is a signal, not a hard trade log
            }));

            return NextResponse.json({ trades: mappedTrades });
        }

        return NextResponse.json({ trades: [] });

    } catch (error) {
        console.error('[TRADES] GET error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
